# Generated by Django 6.0.1 on 2026-01-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="country",
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True, help_text="Введите город", max_length=50, null=True, verbose_name="Город"
            ),
        ),
    ]
