# Generated by Django 6.0.1 on 2026-02-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает оплаты"),
                    ("succeeded", "Оплачено"),
                    ("failed", "Ошибка оплаты"),
                    ("refunded", "Возврат"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус платежа",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_url",
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name="Ссылка на оплату"),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_payment_intent_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="ID платежа в Stripe"),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_price_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="ID цены в Stripe"),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="ID продукта в Stripe"),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="ID сессии в Stripe"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("transfer", "Перевод на счет"), ("card", "Банковская карта")],
                max_length=20,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
