# Generated by Django 6.0.1 on 2026-01-20 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите принадлежность к курсу",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lms.course",
                verbose_name="Курс",
            ),
        ),
    ]
