# Generated by Django 5.2.12 on 2026-03-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_course_created_at_course_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_link",
            field=models.CharField(
                blank=True,
                help_text="Укажите ссылку на видеоматериал",
                max_length=200,
                null=True,
                verbose_name="Ссылка на видео",
            ),
        ),
    ]
